#!/usr/bin/env python3
"""
spec_simplifier_s3.py — Compress a verbose S3 spec to remove noise.

Takes an S3-LLM spec (rich but potentially verbose) and produces a
simplified version by asking LLM to:
  - Shorten purpose to ≤1 sentence
  - Compress semantic_summary to ≤2 sentences, keeping only
    modularization-relevant content (what global state is touched and how)
  - Keep preconditions/postconditions but remove implementation details
  - Strip any domain-specific jargon that doesn't help identify redundancy

The simplified spec retains all structural fields (reads/writes globals,
calls, source_anchor) unchanged — only the semantic text fields are compressed.

Purpose: compare LLM modularization analysis quality before vs after simplification.

Usage:
  python3 spec_simplifier_s3.py <s3_spec.yaml> [output.yaml] [--model <model>]
"""

import argparse
import os
import re
import sys
import textwrap
from pathlib import Path

import anthropic
import yaml


DEFAULT_MODEL = 'anthropic/claude-sonnet-4-6'

SIMPLIFY_SYSTEM = textwrap.dedent("""\
    You are a spec editor. You will receive a YAML spec for a set of functions.
    Each function has verbose semantic descriptions generated by an LLM.

    Your job: compress the semantic fields to remove noise while preserving
    all information useful for identifying code redundancy and modularization.

    For each function, rewrite these fields:
      purpose          → ≤1 sentence, focus on WHAT not HOW
      semantic_summary → ≤2 sentences, keep only: what global state is touched,
                         in what order, and what the observable effect is
      preconditions    → keep only conditions about hw.*/ctrl.* global state;
                         remove implementation-detail conditions
      postconditions   → keep only observable hw.*/ctrl.* state changes;
                         remove internal intermediate states

    DO NOT modify these fields (copy them exactly):
      inputs, returns, calls, reads_globals, writes_globals, source_anchor

    Output ONLY a valid YAML block with the same top-level structure as the input.
    Do not add commentary outside the YAML block.
""")


def make_client() -> anthropic.Anthropic:
    auth_token = os.environ.get('ANTHROPIC_AUTH_TOKEN')
    base_url   = os.environ.get('ANTHROPIC_BASE_URL')
    if auth_token and base_url:
        return anthropic.Anthropic(base_url=base_url, auth_token=auth_token)
    api_key = os.environ.get('ANTHROPIC_API_KEY')
    if api_key:
        return anthropic.Anthropic(api_key=api_key)
    print('Error: set ANTHROPIC_AUTH_TOKEN+ANTHROPIC_BASE_URL or ANTHROPIC_API_KEY',
          file=sys.stderr)
    sys.exit(1)


def extract_yaml_from_response(response: str) -> dict:
    match = re.search(r'```(?:yaml)?\s*\n(.*?)```', response, re.DOTALL)
    yaml_str = match.group(1) if match else response.strip()
    return yaml.safe_load(yaml_str)


def simplify_spec(spec: dict, model: str) -> dict:
    """Call LLM to compress semantic fields; keep all structural fields intact."""
    # Send only the functions block to LLM (meta + structural fields stay untouched)
    functions_yaml = yaml.dump(
        {'functions': spec['functions']},
        allow_unicode=True, sort_keys=False, default_flow_style=False
    )

    client = make_client()
    user_prompt = (
        f"Here is the S3 spec for `{spec['meta']['source_file']}`:\n\n"
        f"```yaml\n{functions_yaml}```\n\n"
        "Please produce the simplified version as described."
    )

    print(f'Calling {model} to simplify spec...')
    message = client.messages.create(
        model=model,
        max_tokens=4096,
        system=SIMPLIFY_SYSTEM,
        messages=[{'role': 'user', 'content': user_prompt}],
    )
    response = message.content[0].text
    simplified_data = extract_yaml_from_response(response)

    # Build output spec: copy meta + module_globals + constants, replace functions
    result = {
        'meta': {
            **spec['meta'],
            'spec_strategy': 'S3-LLM-simplified',
            'generator':     'spec_simplifier_s3.py',
            'note': (
                'Compressed version of S3-LLM spec. '
                'Semantic text fields (purpose, semantic_summary, '
                'preconditions, postconditions) simplified by LLM '
                'to remove noise. Structural fields copied verbatim.'
            ),
        },
        'module_globals': spec.get('module_globals'),
        'constants':      spec.get('constants'),
        'functions':      simplified_data.get('functions', {}),
    }

    # Safety: re-inject source_anchor from original in case LLM dropped it
    for name, fn in result['functions'].items():
        if name in spec['functions'] and 'source_anchor' in spec['functions'][name]:
            fn['source_anchor'] = spec['functions'][name]['source_anchor']

    return result


def _text_len(fn: dict) -> int:
    """Sum of character lengths of all text-based semantic fields."""
    total = 0
    for field in ('purpose', 'semantic_summary'):
        v = fn.get(field)
        if isinstance(v, str):
            total += len(v)
    for field in ('preconditions', 'postconditions'):
        items = fn.get(field) or []
        total += sum(len(s) for s in items if isinstance(s, str))
    return total


def main() -> None:
    parser = argparse.ArgumentParser(description='S3 spec simplifier')
    parser.add_argument('spec', help='S3 spec YAML file')
    parser.add_argument('output', nargs='?',
                        help='Output YAML file (default: *_spec_s3_simplified.yaml)')
    parser.add_argument('--model', default=DEFAULT_MODEL)
    args = parser.parse_args()

    src_path = Path(args.spec)
    spec     = yaml.safe_load(src_path.read_text(encoding='utf-8'))

    stem = src_path.stem.replace('_spec_s3', '')
    out  = Path(args.output) if args.output else \
           src_path.with_name(stem + '_spec_s3_simplified.yaml')

    simplified = simplify_spec(spec, args.model)

    with open(out, 'w', encoding='utf-8') as f:
        yaml.dump(simplified, f, allow_unicode=True, sort_keys=False,
                  default_flow_style=False)

    print(f'Simplified spec written → {out}')

    # Show compression ratio per function
    print(f'\n  Semantic text compression (chars):')
    orig_total = 0
    simp_total = 0
    for name in spec['functions']:
        orig = _text_len(spec['functions'][name])
        simp = _text_len(simplified['functions'].get(name, {}))
        ratio = simp / orig if orig else 1.0
        print(f'    {name:30s}  {orig:5d} → {simp:5d} chars  ({ratio:.0%})')
        orig_total += orig
        simp_total += simp
    overall = simp_total / orig_total if orig_total else 1.0
    print(f'    {"TOTAL":30s}  {orig_total:5d} → {simp_total:5d} chars  ({overall:.0%})')


if __name__ == '__main__':
    main()
